# Generated by Django 6.0.3 on 2026-03-14 17:07

import apps.cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudmedia',
            name='file',
            field=models.FileField(upload_to=apps.cloud.models.get_upload_path),
        ),
    ]
