server {
    listen 80;
    server_name {{LIVE_DOMAIN}}; # Replace with your actual domain if needed

    client_max_body_size 100M;

    # Serve static files
    location /static/ {
        alias {{DEPLOY_PATH}}/{{LIVE_FOLDER}}/static/;
        expires 30d;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Serve media files
    location /media/ {
        alias {{DEPLOY_PATH}}/{{LIVE_FOLDER}}/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://unix:{{DEPLOY_PATH}}/{{LIVE_FOLDER}}/app.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
